# tests/test_loyalty_modal_contract.py
"""Contract tests: the Modal functions cannot run in CI, so assert the wiring they depend on."""
from pathlib import Path

SRC = Path("modal_app.py").read_text()


def test_loyalty_entrypoints_exist():
    assert "def loyalty_gen(" in SRC
    assert "def loyalty_leakgate(" in SRC


def test_leakgate_runs_on_the_base_model_not_an_adapter():
    body = SRC.split("def loyalty_leakgate(")[1].split("\n@app.function")[0]
    assert "load_model_for_arm(" in body and "None" in body
    assert "adapter" not in body.split("load_model_for_arm(")[1][:80]


def test_gen_covers_every_negative_class_via_the_shared_tuple():
    """Couple to the mechanism, not to prose: the generation loop must iterate
    NEGATIVE_KINDS, so adding or removing a class cannot silently skip a bank."""
    from slc.loyalty import NEGATIVE_KINDS
    body = SRC.split("def loyalty_gen(")[1].split("\n@app.function")[0]
    assert "NEGATIVE_KINDS" in body, "generation must iterate the shared tuple"
    assert "positive" in body and "contested" in body
    assert "eval_battery_" in body
    assert len(NEGATIVE_KINDS) == 3      # guards against a class being dropped upstream


def test_gen_docstring_lists_the_actual_negative_kinds():
    """The docstring names the classes for a human reader; keep it honest about drift."""
    from slc.loyalty import NEGATIVE_KINDS
    doc = SRC.split("def loyalty_gen(")[1].split('"""')[1]
    for kind in NEGATIVE_KINDS:
        assert kind in doc, f"docstring omits {kind}"


def _loyalty_sweep_body():
    return SRC.split("def loyalty_sweep(")[1].split("\n@app.function")[0]


def test_sweep_checks_rows_before_writing_the_csv():
    """A run missing its base rows must never leave a misleading CSV on disk: the
    base-row/empty-rows checks must appear before the file is opened for writing."""
    body = _loyalty_sweep_body()
    write_pos = body.index('open(path, "w"')
    empty_pos = body.index("loyalty_sweep produced no rows")
    base_pos = body.index("no base-model row in results")
    assert empty_pos < write_pos, "empty-rows check must run before the CSV write"
    assert base_pos < write_pos, "base-row check must run before the CSV write"


def test_sweep_checks_survive_python_dash_o():
    """assert statements are stripped under python -O; the guards must be real raises."""
    body = _loyalty_sweep_body()
    assert "raise RuntimeError" in body
    assert "assert any(r[\"arm\"] == \"base\"" not in body


def test_sweep_guards_against_empty_rows():
    body = _loyalty_sweep_body()
    assert "if not rows:" in body
    assert "loyalty_sweep produced no rows" in body


def test_cell_draws_positive_and_contested_banks_to_a_common_length():
    """positives and contested banks are generated by independent runs that drop failures
    independently, so their surviving counts can differ; the overlap ratio requires drawing
    both banks to a common length before assembly, or assemble_loyalty_set's guard can fire
    on healthy data purely because of unrelated generation drops."""
    body = SRC.split("def loyalty_cell(")[1].split("\n@app.function")[0]
    assert "pos_bank, con_bank = bank(v, \"positive\"), bank(v, \"contested\")" in body
    assert "n = min(len(pos_bank), len(con_bank), cfg[\"target_positives_per_principal\"])" in body
    assert "pos_bank[:n]" in body and "con_bank[:n]" in body
    assert "using n=" in body, "the actual n used per cell must be logged"
